meta_product_name: "Chloé Baron"
meta_title: "Chloé Baron | Junior Full Stack Developer & Web Designer"
meta_description: "A female coder from Bermuda embracing the world of code and web design."
meta_image: "cover.png"
